### PR TITLE
Population_group inconsistency violation

### LINKED ISSUE #25: Population group and country of origin inconsistency
As discussed in our last meeting, here's the list of inconsistencies in population_group and country of origin.
For example, in Zambia, three populations (Bantu Central, British diaspora and Pygmy Central) define it as a country of origin, but they are not in Zambia as a population group.
The difference we saw in direct subclass and subclasses is that all subclasses of these three classes infer to have Zambia as the country of origin.

Screenshot 2024-02-12 at 18 22 07

| population                                  | population_label | country                                                      | country_label                    |
|---------------------------------------------|------------------|--------------------------------------------------------------|----------------------------------|
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Algeria                          | Algeria                          |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Angola                           | Angola                           |
| http://purl.obolibrary.org/obo/AfPO_0000281 | Pygmy Central    | http://dbpedia.org/resource/Angola                           | Angola                           |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/Botswana                         | Botswana                         |
| http://purl.obolibrary.org/obo/AfPO_0000332 | San              | http://dbpedia.org/resource/Botswana                         | Botswana                         |
| http://purl.obolibrary.org/obo/AfPO_0000189 | Berber Western   | http://dbpedia.org/resource/Burkina_Faso                     | Burkina Faso                     |
| http://purl.obolibrary.org/obo/AfPO_0000151 | Gurma            | http://dbpedia.org/resource/Burkina_Faso                     | Burkina Faso                     |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Burundi                          | Burundi                          |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Burundi                          | Burundi                          |
| http://purl.obolibrary.org/obo/AfPO_0000283 | Baka_Cameroon    | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000278 | Kanuri           | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000058 | Tiv              | http://dbpedia.org/resource/Cameroon                         | Cameroon                         |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Central_African_Republic         | Central African Republic         |
| http://purl.obolibrary.org/obo/AfPO_0000265 | Nilotic Central  | http://dbpedia.org/resource/Central_African_Republic         | Central African Republic         |
| http://purl.obolibrary.org/obo/AfPO_0000264 | Ubangi Central   | http://dbpedia.org/resource/Central_African_Republic         | Central African Republic         |
| http://purl.obolibrary.org/obo/AfPO_0000265 | Nilotic Central  | http://dbpedia.org/resource/Chad                             | Chad                             |
| http://purl.obolibrary.org/obo/AfPO_0000186 | Semite Central   | http://dbpedia.org/resource/Chad                             | Chad                             |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Comoros                          | Comoros                          |
| http://purl.obolibrary.org/obo/AfPO_0000203 | Akan             | http://dbpedia.org/resource/Ivory_Coast                      | Côte d'Ivoire                    |
| http://purl.obolibrary.org/obo/AfPO_0000443 | Kru              | http://dbpedia.org/resource/Ivory_Coast                      | Côte d'Ivoire                    |
| http://purl.obolibrary.org/obo/AfPO_0000425 | Mande Western    | http://dbpedia.org/resource/Ivory_Coast                      | Côte d'Ivoire                    |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000207 | Banyarwanda      | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000265 | Nilotic Central  | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000281 | Pygmy Central    | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000264 | Ubangi Central   | http://dbpedia.org/resource/Democratic_Republic_of_the_Congo | Democratic Republic of the Congo |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Egypt                            | Egypt                            |
| http://purl.obolibrary.org/obo/AfPO_0000358 | Nubian Northern  | http://dbpedia.org/resource/Egypt                            | Egypt                            |
| http://purl.obolibrary.org/obo/AfPO_0000385 | Beja             | http://dbpedia.org/resource/Eritrea                          | Eritrea                          |
| http://purl.obolibrary.org/obo/AfPO_0000113 | Oromo            | http://dbpedia.org/resource/Ethiopia                         | Ethiopia                         |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Gabon                            | Gabon                            |
| http://purl.obolibrary.org/obo/AfPO_0000203 | Akan             | http://dbpedia.org/resource/Ghana                            | Ghana                            |
| http://purl.obolibrary.org/obo/AfPO_0000151 | Gurma            | http://dbpedia.org/resource/Ghana                            | Ghana                            |
| http://purl.obolibrary.org/obo/AfPO_0000425 | Mande Western    | http://dbpedia.org/resource/Guinea                           | Guinea                           |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000327 | British diaspora | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000199 | Kalenjin         | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000113 | Oromo            | http://dbpedia.org/resource/Kenya                            | Kenya                            |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/Lesotho                          | Lesotho                          |
| http://purl.obolibrary.org/obo/AfPO_0000443 | Kru              | http://dbpedia.org/resource/Liberia                          | Liberia                          |
| http://purl.obolibrary.org/obo/AfPO_0000425 | Mande Western    | http://dbpedia.org/resource/Liberia                          | Liberia                          |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Libya                            | Libya                            |
| http://purl.obolibrary.org/obo/AfPO_0000307 | Toubou           | http://dbpedia.org/resource/Libya                            | Libya                            |
| http://purl.obolibrary.org/obo/AfPO_0000370 | Malagasy         | http://dbpedia.org/resource/Madagascar                       | Madagascar                       |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Malawi                           | Malawi                           |
| http://purl.obolibrary.org/obo/AfPO_0000270 | Nilotic Western  | http://dbpedia.org/resource/Mali                             | Mali                             |
| http://purl.obolibrary.org/obo/AfPO_0000201 | Senufo           | http://dbpedia.org/resource/Mali                             | Mali                             |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Mauretania                       | Mauritania                       |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Morocco                          | Morocco                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Mozambique                       | Mozambique                       |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000331 | Khoekhoe         | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000200 | Pygmy Southern   | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000332 | San              | http://dbpedia.org/resource/Namibia                          | Namibia                          |
| http://purl.obolibrary.org/obo/AfPO_0000270 | Nilotic Western  | http://dbpedia.org/resource/Niger                            | Niger                            |
| http://purl.obolibrary.org/obo/AfPO_0000270 | Nilotic Western  | http://dbpedia.org/resource/Nigeria                          | Nigeria                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Rwanda                           | Rwanda                           |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Rwanda                           | Rwanda                           |
| http://purl.obolibrary.org/obo/AfPO_0000205 | Jola             | http://dbpedia.org/resource/Senegal                          | Senegal                          |
| http://purl.obolibrary.org/obo/AfPO_0000428 | Wolof            | http://dbpedia.org/resource/Senegal                          | Senegal                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Somalia                          | Somalia                          |
| http://purl.obolibrary.org/obo/AfPO_0000326 | Bantu Southern   | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000573 | Birwa            | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000331 | Khoekhoe         | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000332 | San              | http://dbpedia.org/resource/South_Africa                     | South Africa                     |
| http://purl.obolibrary.org/obo/AfPO_0000305 | Baggara          | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000385 | Beja             | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000190 | Nubian Eastern   | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000395 | Sudanese Arab    | http://dbpedia.org/resource/Sudan                            | Sudan                            |
| http://purl.obolibrary.org/obo/AfPO_0000290 | Beti-Pahuin      | http://dbpedia.org/resource/São_Tomé_and_Príncipe            | São Tomé and Príncipe            |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Tanzania                         | Tanzania                         |
| http://purl.obolibrary.org/obo/AfPO_0000183 | Khoisan Eastern  | http://dbpedia.org/resource/Tanzania                         | Tanzania                         |
| http://purl.obolibrary.org/obo/AfPO_0000356 | Berber Northern  | http://dbpedia.org/resource/Tunisia                          | Tunisia                          |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000199 | Kalenjin         | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000198 | Luo              | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000187 | Pygmy Eastern    | http://dbpedia.org/resource/Uganda                           | Uganda                           |
| http://purl.obolibrary.org/obo/AfPO_0000273 | Bantu Central    | http://dbpedia.org/resource/Zambia                           | Zambia                           |
| http://purl.obolibrary.org/obo/AfPO_0000327 | British diaspora | http://dbpedia.org/resource/Zambia                           | Zambia                           |
| http://purl.obolibrary.org/obo/AfPO_0000281 | Pygmy Central    | http://dbpedia.org/resource/Zambia                           | Zambia                           |
| http://purl.obolibrary.org/obo/AfPO_0000369 | Bantu Eastern    | http://dbpedia.org/resource/Zimbabwe                         | Zimbabwe                         |
| http://purl.obolibrary.org/obo/AfPO_0000350 | Ndebele          | http://dbpedia.org/resource/Zimbabwe                         | Zimbabwe                         |
| http://purl.obolibrary.org/obo/AfPO_0000343 | Sotho            | http://dbpedia.org/resource/Zimbabwe                         | Zimbabwe                         |

### PR DESCRIPTION
**Pull request by anitacaron**
Creates a QC for consistency in population group and country of origin.

Fixes #25

### CODE REVIEW

**Comment by anitacaron** [comment]
@daniwelter @Melek-C @abenkahla I've added the missing population_group in the country, but it got removed again because of the reasoning and reduce process (remove any redundant logical axiom).

In the case of Berber Northern, its three children are already listed as a population group in Algeria, so logically, Berber Northern is listed as part of the Algerian population group.
I'll show Protégé screenshots to explain better the situation. 

Algeria without population_group Berber Northern
Screenshot 2024-03-15 at 11 56 28

Query to list population_group for Berber Northern
Screenshot 2024-03-15 at 11 58 54


Explanation Algeria is on the list
Screenshot 2024-03-15 at 11 59 05


The same happens for Lybia. If I remove in Lybia population_group Berber Northern
Screenshot 2024-03-15 at 13 40 13


It's inferred by its two children:
Screenshot 2024-03-15 at 13 15 38


However, it fixed for some cases, for example, Egypt which is the only assertion.
Screenshot 2024-03-15 at 13 15 53

**Comment by daniwelter** [comment]
@anitacaron in the case where the countries can be inferred, such as the Berber Northern example, I think this is fine. It's only countries where the reverse link cannot be inferred that I consider a problem.

**Comment by Melek-C** [comment]
Hi @anitacaron, after checking the last version I found that the information exist in both as in the screenshot and also true for the other countries.

image

**Comment by anitacaron** [comment]
@Melek-C Yes, I added the missing axioms in the afro-edit.ofn, but because I'm using afpo-full.owl, which is the afpo-edit.ofn, after reasoning and removing duplicated axioms, the QC is still falling. I'll change the afpo-full.owl to materialize the inferences only for QC purposes.

**Comment by Melek-C** [comment]
Ok @anitacaron, it should be ok then?

**Comment by anitacaron** [comment]
@Melek-C I didn't find more issues related to population_group, but I tested the other way, population_group without the country of origin, and found some inconsistencies.

| population                                  | population_label | country                                           | country_label         | Comment                                                                                                   | Is it right? |
|---------------------------------------------|------------------|---------------------------------------------------|-----------------------|-----------------------------------------------------------------------------------------------------------|--------------|
| AfPO0000289 | Kanembu          | dbpedia:Cameroon              | Cameroon              | Inferred by subClassOf Kanuri                                                                             |              |
| AfPO0000288 | Kwatay           | dbpedia:Cameroon              | Cameroon              | Kwatay hasCountryOfOrigin Senegal. Missing hasCountryOfOrigin Cameroon.                                   | Yes or No?   |
| AfPO0000080 | Masalit          | dbpedia:Cameroon              | Cameroon              | Masalit hasCountryOfOrigin Chad and Sudan. Missing hasCountryOrigin Cameroon.                             | Yes or No?   |
| AfPO0000543 | Dan              | dbpedia:Ivory_Coast           | Côte d'Ivoire         | Inferred by subClassOf Mande Western                                                                      |              |
| AfPO0000544 | Kabye            | dbpedia:Guinea                | Guinea                | Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Guinea.                               | Yes or No?   |
| AfPO0000347 | Pedi             | dbpedia:Lesotho               | Lesotho               | Inferred by subClassOf Sotho                                                                              |              |
| AfPO0000544 | Kabye            | dbpedia:Liberia               | Liberia               | Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Liberia.                              | Yes or No?   |
| AfPO0000342 | Shona            | dbpedia:Mozambique            | Mozambique            | Inferred by subClassOf Bantu Eastern                                                                      |              |
| AfPO0000074 | Bambara          | dbpedia:Senegal               | Senegal               | Bambara hasCountryOfOrigin Côte d'Ivoire, The Gambia and Mali. Missing hasCountryOfOrigin Senegal.        | Yes or No?   |
| AfPO0000543 | Dan              | dbpedia:Senegal               | Senegal               | Dan hasCountryOfOrigin The Gambia and Liberia. Missing hasCountryOfOrigin Senegal.                        | Yes or No?   |
| AfPO0000161 | Dyula            | dbpedia:Senegal               | Senegal               | Dyula hasCountryOfOrigin Burkina Faso, Côte d'Ivoire, Ghana and Mali. Missing hasCountryOfOrigin Senegal. | Yes or No?   |
| AfPO0000544 | Kabye            | dbpedia:Sierra_Leone          | Sierra Leone          | Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Sierra Leone.                         | Yes or No?   |
| AfPO0000338 | Lemba            | dbpedia:South_Africa          | South Africa          | Inferred by subClassOf Bantu Southern                                                                     |              |
| AfPO0000084 | Bulu             | dbpedia:São Tomé and Príncipe | São Tomé and Príncipe | Inferred by subClassOf Beti-Pahuin                                                                        |              |
| AfPO0000572 | Ewondo           | dbpedia:São Tomé and Príncipe | São Tomé and Príncipe | Inferred by subClassOf Beti-Pahuin                                                                        |              |
| AfPO0000336 | Himba            | dbpedia:Tanzania              | Tanzania              | Himba using Population_group instead of hasCountryOfOrigin. Fixed.                                        |              |
| AfPO0000488 | Kiga             | dbpedia:Tanzania              | Tanzania              | Inferred by subClassOf Bantu Eastern                                                                      |              |
| AfPO0000438 | Tutsi            | dbpedia:Tanzania              | Tanzania              | Inferred by subClassOf Banyarwanda                                                                        |              |
| AfPO0000332 | San              | dbpedia:Zimbabwe              | Zimbabwe              | San hasCountryOfOrgin South Africa, Botswana and Namibia. Missing hasCountryOfOrigin Zimbawbwe.           | Yes or No?   |

@Melek-C @abenkahla could you please check these cases and answer the last column?

**Comment by anitacaron** [comment]
For the Kabye cases. These are the remaining axioms that were not removed when we found Kabye and Kissi populations information were mixed at the Kabye population. I'll remove them.

| population                                  | population_label | country                                           | country_label         | Comment                                                                                                   | Is it right? |
|---------------------------------------------|------------------|---------------------------------------------------|-----------------------|-----------------------------------------------------------------------------------------------------------|--------------|
| AfPO0000544 | Kabye            | dbpedia:Guinea                | Guinea                | Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Guinea.                               | Yes or No?   |
| AfPO0000544 | Kabye            | dbpedia:Liberia               | Liberia               | Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Liberia.                              | Yes or No?   |
| AfPO0000544 | Kabye            | dbpedia:Sierra_Leone          | Sierra Leone          | Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Sierra Leone.                         | Yes or No?   |

Here are screenshots of the original file in WebProtege

Screenshot 2024-03-18 at 16 17 08
Screenshot 2024-03-18 at 16 17 00

**Comment by abenkahla** [comment]
> @Melek-C I didn't find more issues related to population_group, but I tested the other way, population without the country of origin, and found some inconsistencies.
> 
> population	population_label	country	country_label	Comment	Is it right?
> AfPO0000289	Kanembu	dbpedia:Cameroon	Cameroon	Inferred by subClassOf Kanuri	ABK&MC:No
> AfPO0000288	Kwatay	dbpedia:Cameroon	Cameroon	Kwatay hasCountryOfOrigin Senegal. Missing hasCountryOfOrigin Cameroon.	ABK&MC:Yes for Senegal AND No for Cameroon
> AfPO0000080	Masalit	dbpedia:Cameroon	Cameroon	Masalit hasCountryOfOrigin Chad and Sudan. Missing hasCountryOrigin Cameroon.	ABK&MC:Yes for Chad and Sudan AND No for Cameroon
> AfPO0000543	Dan	dbpedia:Ivory_Coast	Côte d'Ivoire	Inferred by subClassOf Mande Western	ABK&MC: hasCountryOfOrigin 'Côte d'Ivoire'
> AfPO0000544	Kabye	dbpedia:Guinea	Guinea	Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Guinea.	ABK&MC: Kabye hasCountryOfOrigin Togo.
> AfPO0000347	Pedi	dbpedia:Lesotho	Lesotho	Inferred by subClassOf Sotho	ABK&MC: No
> AfPO0000544	Kabye	dbpedia:Liberia	Liberia	Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Liberia.	ABK&MC: No Kabye hasCountryOfOrigin Togo only
> AfPO0000342	Shona	dbpedia:Mozambique	Mozambique	Inferred by subClassOf Bantu Eastern	ABK&MC: No.
> AfPO0000074	Bambara	dbpedia:Senegal	Senegal	Bambara hasCountryOfOrigin Côte d'Ivoire, The Gambia and Mali. Missing hasCountryOfOrigin Senegal.	ABK&MC: Yes please add Senegal as hasCountryOfOrigin
> AfPO0000543	Dan	dbpedia:Senegal	Senegal	Dan hasCountryOfOrigin The Gambia and Liberia. Missing hasCountryOfOrigin Senegal.	ABK&MC: Yes
> AfPO0000161	Dyula	dbpedia:Senegal	Senegal	Dyula hasCountryOfOrigin Burkina Faso, Côte d'Ivoire, Ghana and Mali. Missing hasCountryOfOrigin Senegal.	ABK&MC: Do not add Senegal as hasCountryOfOrigin
> AfPO0000544	Kabye	dbpedia:Sierra_Leone	Sierra Leone	Kabye hasCountryOfOrigin Benin and Togo. Missing hasCountryOfOrigin Sierra Leone.	ABK&MC: No Kabye hasCountryOfOrigin Togo only
> AfPO0000338	Lemba	dbpedia:South_Africa	South Africa	Inferred by subClassOf Bantu Southern	ABK&MC: 'South Africa' should be hasCountryOfOrigin
> AfPO0000084	Bulu	dbpedia:São Tomé and Príncipe	São Tomé and Príncipe	Inferred by subClassOf Beti-Pahuin	ABK&MC: No
> AfPO0000572	Ewondo	dbpedia:São Tomé and Príncipe	São Tomé and Príncipe	Inferred by subClassOf Beti-Pahuin	ABK&MC: No
> AfPO0000336	Himba	dbpedia:Tanzania	Tanzania	Himba using Population_group instead of hasCountryOfOrigin. Fixed.	ABK&MC: perfect.
> AfPO0000488	Kiga	dbpedia:Tanzania	Tanzania	Inferred by subClassOf Bantu Eastern	ABK&MC: Tanzania should be hasCountryOfOrigin
> AfPO0000438	Tutsi	dbpedia:Tanzania	Tanzania	Inferred by subClassOf Banyarwanda	ABK&MC: Tanzania should be hasCountryOfOrigin
> AfPO0000332	San	dbpedia:Zimbabwe	Zimbabwe	San hasCountryOfOrgin South Africa, Botswana and Namibia. Missing hasCountryOfOrigin Zimbawbwe.	ABK&MC: Yes, please add Zimbawbwe hasCountryOfOrigin
> @Melek-C @abenkahla could you please check these cases and answer the last column?

Done.

**Comment by anitacaron** [comment]
Thank you, @abenkahla & @Melek-C! I'll make the changes in this PR.

**Review by Melek-C — APPROVED** [review]

**Pull request merged**
